workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    novu-OAS:
        inputs:
            - location: http://127.0.0.1:3000/openapi.sdk.yaml
        registry:
            location: registry.speakeasyapi.dev/novu/novu/novu-oas
targets:
    novu:
        target: php
        source: novu-OAS
        publish:
            packagist:
                username: novuhq
                token: $packagist_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/novu/novu/novu-oas-php-code-samples
            labelOverride:
                fixedValue: Php (SDK)
            blocking: false
