<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class ActivityControllerGetLogsRequest
{
    /**
     * Page number for pagination
     *
     * @var ?float $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?float $page = null;

    /**
     * Number of items per page
     *
     * @var ?float $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?float $limit = null;

    /**
     * Filter by HTTP status codes
     *
     * @var ?array<float> $statusCodes
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=statusCodes')]
    public ?array $statusCodes = null;

    /**
     * Filter by request URL
     *
     * @var ?string $url
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=url')]
    public ?string $url = null;

    /**
     * Filter by URL pattern
     *
     * @var ?string $urlPattern
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=url_pattern')]
    public ?string $urlPattern = null;

    /**
     * Filter by transaction identifier
     *
     * @var ?string $transactionId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=transactionId')]
    public ?string $transactionId = null;

    /**
     * Filter requests created after this timestamp (Unix timestamp)
     *
     * @var ?float $createdGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=createdGte')]
    public ?float $createdGte = null;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  ?float  $page
     * @param  ?float  $limit
     * @param  ?array<float>  $statusCodes
     * @param  ?string  $url
     * @param  ?string  $urlPattern
     * @param  ?string  $transactionId
     * @param  ?float  $createdGte
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(?float $page = null, ?float $limit = null, ?array $statusCodes = null, ?string $url = null, ?string $urlPattern = null, ?string $transactionId = null, ?float $createdGte = null, ?string $idempotencyKey = null)
    {
        $this->page = $page;
        $this->limit = $limit;
        $this->statusCodes = $statusCodes;
        $this->url = $url;
        $this->urlPattern = $urlPattern;
        $this->transactionId = $transactionId;
        $this->createdGte = $createdGte;
        $this->idempotencyKey = $idempotencyKey;
    }
}