<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class AgentsControllerUpdateAgentBridgeRequest
{
    /**
     *
     * @var string $identifier
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=identifier')]
    public string $identifier;

    /**
     *
     * @var \novu\Models\Components\UpdateAgentBridgeRequestDto $updateAgentBridgeRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\UpdateAgentBridgeRequestDto $updateAgentBridgeRequestDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $identifier
     * @param  \novu\Models\Components\UpdateAgentBridgeRequestDto  $updateAgentBridgeRequestDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $identifier, Components\UpdateAgentBridgeRequestDto $updateAgentBridgeRequestDto, ?string $idempotencyKey = null)
    {
        $this->identifier = $identifier;
        $this->updateAgentBridgeRequestDto = $updateAgentBridgeRequestDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}