<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class ChannelConnectionsControllerDeleteChannelConnectionRequest
{
    /**
     * The unique identifier of the channel connection
     *
     * @var string $identifier
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=identifier')]
    public string $identifier;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $identifier
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $identifier, ?string $idempotencyKey = null)
    {
        $this->identifier = $identifier;
        $this->idempotencyKey = $idempotencyKey;
    }
}