<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class ChannelEndpointsControllerListChannelEndpointsRequest
{
    /**
     * Cursor for pagination indicating the starting point after which to fetch results.
     *
     * @var ?string $after
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=after')]
    public ?string $after = null;

    /**
     * Cursor for pagination indicating the ending point before which to fetch results.
     *
     * @var ?string $before
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=before')]
    public ?string $before = null;

    /**
     * Limit the number of items to return (max 100)
     *
     * @var ?float $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?float $limit = null;

    /**
     * Direction of sorting
     *
     * @var ?ChannelEndpointsControllerListChannelEndpointsQueryParamOrderDirection $orderDirection
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=orderDirection')]
    public ?ChannelEndpointsControllerListChannelEndpointsQueryParamOrderDirection $orderDirection = null;

    /**
     * Field to order by
     *
     * @var ?string $orderBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=orderBy')]
    public ?string $orderBy = null;

    /**
     * Include cursor item in response
     *
     * @var ?bool $includeCursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeCursor')]
    public ?bool $includeCursor = null;

    /**
     * The subscriber ID to filter results by
     *
     * @var ?string $subscriberId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=subscriberId')]
    public ?string $subscriberId = null;

    /**
     * Filter by exact context keys, order insensitive (format: "type:id")
     *
     * @var ?array<string> $contextKeys
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=contextKeys')]
    public ?array $contextKeys = null;

    /**
     * Channel type to filter results.
     *
     * @var ?QueryParamChannel $channel
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=channel')]
    public ?QueryParamChannel $channel = null;

    /**
     * Filter by provider identifier (e.g., sendgrid, twilio, slack, etc.).
     *
     * @var ?Components\ProvidersIdEnum $providerId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=providerId')]
    public ?Components\ProvidersIdEnum $providerId = null;

    /**
     * Integration identifier to filter results.
     *
     * @var ?string $integrationIdentifier
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=integrationIdentifier')]
    public ?string $integrationIdentifier = null;

    /**
     * Connection identifier to filter results.
     *
     * @var ?string $connectionIdentifier
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=connectionIdentifier')]
    public ?string $connectionIdentifier = null;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  ?string  $after
     * @param  ?string  $before
     * @param  ?float  $limit
     * @param  ?ChannelEndpointsControllerListChannelEndpointsQueryParamOrderDirection  $orderDirection
     * @param  ?string  $orderBy
     * @param  ?bool  $includeCursor
     * @param  ?string  $subscriberId
     * @param  ?array<string>  $contextKeys
     * @param  ?QueryParamChannel  $channel
     * @param  ?Components\ProvidersIdEnum  $providerId
     * @param  ?string  $integrationIdentifier
     * @param  ?string  $connectionIdentifier
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(?string $after = null, ?string $before = null, ?float $limit = null, ?ChannelEndpointsControllerListChannelEndpointsQueryParamOrderDirection $orderDirection = null, ?string $orderBy = null, ?bool $includeCursor = null, ?string $subscriberId = null, ?array $contextKeys = null, ?QueryParamChannel $channel = null, ?Components\ProvidersIdEnum $providerId = null, ?string $integrationIdentifier = null, ?string $connectionIdentifier = null, ?string $idempotencyKey = null)
    {
        $this->after = $after;
        $this->before = $before;
        $this->limit = $limit;
        $this->orderDirection = $orderDirection;
        $this->orderBy = $orderBy;
        $this->includeCursor = $includeCursor;
        $this->subscriberId = $subscriberId;
        $this->contextKeys = $contextKeys;
        $this->channel = $channel;
        $this->providerId = $providerId;
        $this->integrationIdentifier = $integrationIdentifier;
        $this->connectionIdentifier = $connectionIdentifier;
        $this->idempotencyKey = $idempotencyKey;
    }
}