<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;



enum Criticality: string
{
    case Critical = 'critical';
    case NonCritical = 'nonCritical';
    case All = 'all';
}
