<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class DomainsControllerUpdateDomainRouteRequest
{
    /**
     *
     * @var string $domain
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=domain')]
    public string $domain;

    /**
     *
     * @var string $address
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=address')]
    public string $address;

    /**
     *
     * @var \novu\Models\Components\UpdateDomainRouteDto $updateDomainRouteDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\UpdateDomainRouteDto $updateDomainRouteDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $domain
     * @param  string  $address
     * @param  \novu\Models\Components\UpdateDomainRouteDto  $updateDomainRouteDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $domain, string $address, Components\UpdateDomainRouteDto $updateDomainRouteDto, ?string $idempotencyKey = null)
    {
        $this->domain = $domain;
        $this->address = $address;
        $this->updateDomainRouteDto = $updateDomainRouteDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}