<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class EnvironmentsControllerV1DeleteEnvironmentRequest
{
    /**
     * The unique identifier of the environment
     *
     * @var string $environmentId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=environmentId')]
    public string $environmentId;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $environmentId
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $environmentId, ?string $idempotencyKey = null)
    {
        $this->environmentId = $environmentId;
        $this->idempotencyKey = $idempotencyKey;
    }
}