<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class EnvironmentVariablesControllerListEnvironmentVariablesRequest
{
    /**
     * Filter variables by key (case-insensitive partial match)
     *
     * @var ?string $search
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  ?string  $search
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(?string $search = null, ?string $idempotencyKey = null)
    {
        $this->search = $search;
        $this->idempotencyKey = $idempotencyKey;
    }
}