<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class EventsControllerTriggerBulkRequest
{
    /**
     *
     * @var Components\BulkTriggerEventDto $bulkTriggerEventDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\BulkTriggerEventDto $bulkTriggerEventDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  Components\BulkTriggerEventDto  $bulkTriggerEventDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(Components\BulkTriggerEventDto $bulkTriggerEventDto, ?string $idempotencyKey = null)
    {
        $this->bulkTriggerEventDto = $bulkTriggerEventDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}