<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class EventsControllerBroadcastEventToAllRequest
{
    /**
     *
     * @var Components\TriggerEventToAllRequestDto $triggerEventToAllRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\TriggerEventToAllRequestDto $triggerEventToAllRequestDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  Components\TriggerEventToAllRequestDto  $triggerEventToAllRequestDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(Components\TriggerEventToAllRequestDto $triggerEventToAllRequestDto, ?string $idempotencyKey = null)
    {
        $this->triggerEventToAllRequestDto = $triggerEventToAllRequestDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}