<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class IntegrationsControllerCreateIntegrationRequest
{
    /**
     *
     * @var Components\CreateIntegrationRequestDto $createIntegrationRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateIntegrationRequestDto $createIntegrationRequestDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  Components\CreateIntegrationRequestDto  $createIntegrationRequestDto
     * @param  ?string  $idempotencyKey
     */
    public function __construct(Components\CreateIntegrationRequestDto $createIntegrationRequestDto, ?string $idempotencyKey = null)
    {
        $this->createIntegrationRequestDto = $createIntegrationRequestDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}