<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class IntegrationsControllerGenerateLinkUserOAuthUrlRequest
{
    /**
     *
     * @var \novu\Models\Components\GenerateLinkUserOauthUrlRequestDto $generateLinkUserOauthUrlRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\GenerateLinkUserOauthUrlRequestDto $generateLinkUserOauthUrlRequestDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  \novu\Models\Components\GenerateLinkUserOauthUrlRequestDto  $generateLinkUserOauthUrlRequestDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(Components\GenerateLinkUserOauthUrlRequestDto $generateLinkUserOauthUrlRequestDto, ?string $idempotencyKey = null)
    {
        $this->generateLinkUserOauthUrlRequestDto = $generateLinkUserOauthUrlRequestDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}