<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class LayoutsControllerGetRequest
{
    /**
     *
     * @var string $layoutId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=layoutId')]
    public string $layoutId;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $layoutId
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $layoutId, ?string $idempotencyKey = null)
    {
        $this->layoutId = $layoutId;
        $this->idempotencyKey = $idempotencyKey;
    }
}