<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;


/** the preferences level to be retrieved (template / global)  */
enum Parameter: string
{
    case Global = 'global';
    case Template = 'template';
}
