<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class SubscribersControllerDeleteSubscriberCredentialsRequest
{
    /**
     *
     * @var string $subscriberId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscriberId')]
    public string $subscriberId;

    /**
     *
     * @var string $providerId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=providerId')]
    public string $providerId;

    /**
     * @param  string  $subscriberId
     * @param  string  $providerId
     */
    public function __construct(string $subscriberId, string $providerId)
    {
        $this->subscriberId = $subscriberId;
        $this->providerId = $providerId;
    }
}