<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class SubscribersControllerGetNotificationsFeedRequest
{
    /**
     *
     * @var string $subscriberId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscriberId')]
    public string $subscriberId;

    /**
     *
     * @var ?float $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?float $page = null;

    /**
     *
     * @var ?bool $read
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=read')]
    public ?bool $read = null;

    /**
     *
     * @var ?bool $seen
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=seen')]
    public ?bool $seen = null;

    /**
     * Base64 encoded string of the partial payload JSON object
     *
     * @var ?string $payload
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=payload')]
    public ?string $payload = null;

    /**
     *
     * @var ?float $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?float $limit = null;

    /**
     * @param  string  $subscriberId
     * @param  ?float  $page
     * @param  ?float  $limit
     * @param  ?bool  $read
     * @param  ?bool  $seen
     * @param  ?string  $payload
     */
    public function __construct(string $subscriberId, ?float $page = null, ?bool $read = null, ?bool $seen = null, ?string $payload = null, ?float $limit = 10)
    {
        $this->subscriberId = $subscriberId;
        $this->page = $page;
        $this->read = $read;
        $this->seen = $seen;
        $this->payload = $payload;
        $this->limit = $limit;
    }
}