<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class SubscribersControllerUpdateSubscriberPreferencesRequest
{
    /**
     *
     * @var string $subscriberId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscriberId')]
    public string $subscriberId;

    /**
     *
     * @var Components\PatchSubscriberPreferencesDto $patchSubscriberPreferencesDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\PatchSubscriberPreferencesDto $patchSubscriberPreferencesDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $subscriberId
     * @param  Components\PatchSubscriberPreferencesDto  $patchSubscriberPreferencesDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $subscriberId, Components\PatchSubscriberPreferencesDto $patchSubscriberPreferencesDto, ?string $idempotencyKey = null)
    {
        $this->subscriberId = $subscriberId;
        $this->patchSubscriberPreferencesDto = $patchSubscriberPreferencesDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}