<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class SubscribersControllerRevertNotificationActionRequest
{
    /**
     * The identifier of the subscriber
     *
     * @var string $subscriberId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscriberId')]
    public string $subscriberId;

    /**
     * The identifier of the notification
     *
     * @var string $notificationId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=notificationId')]
    public string $notificationId;

    /**
     * The type of action (primary or secondary)
     *
     * @var \novu\Models\Operations\PathParamActionType $actionType
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=actionType')]
    public PathParamActionType $actionType;

    /**
     * Context keys for filtering
     *
     * @var ?array<string> $contextKeys
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=contextKeys')]
    public ?array $contextKeys = null;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $subscriberId
     * @param  string  $notificationId
     * @param  \novu\Models\Operations\PathParamActionType  $actionType
     * @param  ?array<string>  $contextKeys
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $subscriberId, string $notificationId, PathParamActionType $actionType, ?array $contextKeys = null, ?string $idempotencyKey = null)
    {
        $this->subscriberId = $subscriberId;
        $this->notificationId = $notificationId;
        $this->actionType = $actionType;
        $this->contextKeys = $contextKeys;
        $this->idempotencyKey = $idempotencyKey;
    }
}