<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class TranslationControllerDeleteTranslationGroupEndpointRequest
{
    /**
     * Resource type
     *
     * @var TranslationControllerDeleteTranslationGroupEndpointPathParamResourceType $resourceType
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=resourceType')]
    public TranslationControllerDeleteTranslationGroupEndpointPathParamResourceType $resourceType;

    /**
     * Resource ID
     *
     * @var string $resourceId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=resourceId')]
    public string $resourceId;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  TranslationControllerDeleteTranslationGroupEndpointPathParamResourceType  $resourceType
     * @param  string  $resourceId
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(TranslationControllerDeleteTranslationGroupEndpointPathParamResourceType $resourceType, string $resourceId, ?string $idempotencyKey = null)
    {
        $this->resourceType = $resourceType;
        $this->resourceId = $resourceId;
        $this->idempotencyKey = $idempotencyKey;
    }
}