<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class TranslationControllerUploadTranslationFilesRequest
{
    /**
     * Translation files upload body details
     *
     * @var Components\UploadTranslationsRequestDto $uploadTranslationsRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=multipart/form-data')]
    public Components\UploadTranslationsRequestDto $uploadTranslationsRequestDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  Components\UploadTranslationsRequestDto  $uploadTranslationsRequestDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(Components\UploadTranslationsRequestDto $uploadTranslationsRequestDto, ?string $idempotencyKey = null)
    {
        $this->uploadTranslationsRequestDto = $uploadTranslationsRequestDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}