<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class WorkflowControllerGeneratePreviewRequest
{
    /**
     *
     * @var string $workflowId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workflowId')]
    public string $workflowId;

    /**
     *
     * @var string $stepId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=stepId')]
    public string $stepId;

    /**
     * Preview generation details
     *
     * @var \novu\Models\Components\GeneratePreviewRequestDto $generatePreviewRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\GeneratePreviewRequestDto $generatePreviewRequestDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $workflowId
     * @param  string  $stepId
     * @param  \novu\Models\Components\GeneratePreviewRequestDto  $generatePreviewRequestDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $workflowId, string $stepId, Components\GeneratePreviewRequestDto $generatePreviewRequestDto, ?string $idempotencyKey = null)
    {
        $this->workflowId = $workflowId;
        $this->stepId = $stepId;
        $this->generatePreviewRequestDto = $generatePreviewRequestDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}