<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Utils\SpeakeasyMetadata;
class WorkflowControllerRemoveWorkflowRequest
{
    /**
     *
     * @var string $workflowId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workflowId')]
    public string $workflowId;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  string  $workflowId
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(string $workflowId, ?string $idempotencyKey = null)
    {
        $this->workflowId = $workflowId;
        $this->idempotencyKey = $idempotencyKey;
    }
}