<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Operations;

use novu\Models\Components;
use novu\Utils\SpeakeasyMetadata;
class WorkflowControllerCreateRequest
{
    /**
     * Workflow creation details
     *
     * @var Components\CreateWorkflowDto $createWorkflowDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateWorkflowDto $createWorkflowDto;

    /**
     * A header for idempotency purposes
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  Components\CreateWorkflowDto  $createWorkflowDto
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(Components\CreateWorkflowDto $createWorkflowDto, ?string $idempotencyKey = null)
    {
        $this->createWorkflowDto = $createWorkflowDto;
        $this->idempotencyKey = $idempotencyKey;
    }
}