<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class ActivityNotificationStepResponseDto
{
    /**
     * Unique identifier of the step
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_id')]
    public string $id;

    /**
     * Whether the step is active or not
     *
     * @var bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    public bool $active;

    /**
     * Filter criteria for the step
     *
     * @var array<StepFilterDto> $filters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filters')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\StepFilterDto>')]
    public array $filters;

    /**
     * The identifier for the template associated with this step
     *
     * @var string $templateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_templateId')]
    public string $templateId;

    /**
     * Reply callback settings
     *
     * @var ?ActivityNotificationStepResponseDtoReplyCallback $replyCallback
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('replyCallback')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ActivityNotificationStepResponseDtoReplyCallback|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ActivityNotificationStepResponseDtoReplyCallback $replyCallback = null;

    /**
     * Control variables
     *
     * @var ?ControlVariables $controlVariables
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('controlVariables')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ControlVariables|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ControlVariables $controlVariables = null;

    /**
     * Metadata for the workflow step
     *
     * @var ?Metadata $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Metadata|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Metadata $metadata = null;

    /**
     * Step issues
     *
     * @var ?Issues $issues
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issues')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Issues|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Issues $issues = null;

    /**
     * Optional template for the step
     *
     * @var ?MessageTemplateDto $template
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('template')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\MessageTemplateDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MessageTemplateDto $template = null;

    /**
     * Variants of the step
     *
     * @var ?array<ActivityNotificationStepResponseDto> $variants
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variants')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\ActivityNotificationStepResponseDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $variants = null;

    /**
     * The name of the step
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The unique identifier for the parent step
     *
     * @var ?string $parentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_parentId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $parentId = null;

    /**
     * @param  string  $id
     * @param  bool  $active
     * @param  array<StepFilterDto>  $filters
     * @param  string  $templateId
     * @param  ?ActivityNotificationStepResponseDtoReplyCallback  $replyCallback
     * @param  ?ControlVariables  $controlVariables
     * @param  ?Metadata  $metadata
     * @param  ?Issues  $issues
     * @param  ?MessageTemplateDto  $template
     * @param  ?array<ActivityNotificationStepResponseDto>  $variants
     * @param  ?string  $name
     * @param  ?string  $parentId
     */
    public function __construct(string $id, bool $active, array $filters, string $templateId, ?ActivityNotificationStepResponseDtoReplyCallback $replyCallback = null, ?ControlVariables $controlVariables = null, ?Metadata $metadata = null, ?Issues $issues = null, ?MessageTemplateDto $template = null, ?array $variants = null, ?string $name = null, ?string $parentId = null)
    {
        $this->id = $id;
        $this->active = $active;
        $this->filters = $filters;
        $this->templateId = $templateId;
        $this->replyCallback = $replyCallback;
        $this->controlVariables = $controlVariables;
        $this->metadata = $metadata;
        $this->issues = $issues;
        $this->template = $template;
        $this->variants = $variants;
        $this->name = $name;
        $this->parentId = $parentId;
    }
}