<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class ActivityNotificationJobResponseDto
{
    /**
     * Unique identifier of the job
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_id')]
    public string $id;

    /**
     * Type of the job
     *
     * @var ActivityNotificationJobResponseDtoType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ActivityNotificationJobResponseDtoType')]
    public ActivityNotificationJobResponseDtoType $type;

    /**
     * Execution details of the job
     *
     * @var array<ActivityNotificationExecutionDetailResponseDto> $executionDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('executionDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\ActivityNotificationExecutionDetailResponseDto>')]
    public array $executionDetails;

    /**
     * Step details of the job
     *
     * @var ActivityNotificationStepResponseDto $step
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('step')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ActivityNotificationStepResponseDto')]
    public ActivityNotificationStepResponseDto $step;

    /**
     * Provider ID of the job
     *
     * @var ProvidersIdEnum $providerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providerId')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ProvidersIdEnum')]
    public ProvidersIdEnum $providerId;

    /**
     * Status of the job
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     * Optional digest for the job, including metadata and events
     *
     * @var ?DigestMetadataDto $digest
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('digest')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\DigestMetadataDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DigestMetadataDto $digest = null;

    /**
     * Optional context object for additional error details.
     *
     * @var ?array<string, mixed> $overrides
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('overrides')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $overrides = null;

    /**
     * Optional payload for the job
     *
     * @var ?ActivityNotificationJobResponseDtoPayload $payload
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payload')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ActivityNotificationJobResponseDtoPayload|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ActivityNotificationJobResponseDtoPayload $payload = null;

    /**
     * Updated time of the notification
     *
     * @var ?string $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $updatedAt = null;

    /**
     * The number of times the digest/delay job has been extended to align with the subscribers schedule
     *
     * @var ?float $scheduleExtensionsCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scheduleExtensionsCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $scheduleExtensionsCount = null;

    /**
     * @param  string  $id
     * @param  ActivityNotificationJobResponseDtoType  $type
     * @param  array<ActivityNotificationExecutionDetailResponseDto>  $executionDetails
     * @param  ActivityNotificationStepResponseDto  $step
     * @param  ProvidersIdEnum  $providerId
     * @param  string  $status
     * @param  ?DigestMetadataDto  $digest
     * @param  ?array<string, mixed>  $overrides
     * @param  ?ActivityNotificationJobResponseDtoPayload  $payload
     * @param  ?string  $updatedAt
     * @param  ?float  $scheduleExtensionsCount
     * @phpstan-pure
     */
    public function __construct(string $id, ActivityNotificationJobResponseDtoType $type, array $executionDetails, ActivityNotificationStepResponseDto $step, ProvidersIdEnum $providerId, string $status, ?DigestMetadataDto $digest = null, ?array $overrides = null, ?ActivityNotificationJobResponseDtoPayload $payload = null, ?string $updatedAt = null, ?float $scheduleExtensionsCount = null)
    {
        $this->id = $id;
        $this->type = $type;
        $this->executionDetails = $executionDetails;
        $this->step = $step;
        $this->providerId = $providerId;
        $this->status = $status;
        $this->digest = $digest;
        $this->overrides = $overrides;
        $this->payload = $payload;
        $this->updatedAt = $updatedAt;
        $this->scheduleExtensionsCount = $scheduleExtensionsCount;
    }
}