<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class AgentReplyPayloadDto
{
    /**
     * Conversation id to reply into. Obtained from the inbound agent event / bridge payload.
     *
     * @var string $conversationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conversationId')]
    public string $conversationId;

    /**
     * Channel integration identifier linked to the agent for this conversation (e.g. `slack-support`).
     *
     * @var string $integrationIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('integrationIdentifier')]
    public string $integrationIdentifier;

    /**
     * Outbound message content. Exactly one of `markdown`, `card`, or `toolApprovalCard`. Optional `files` attach to the message. Cannot be combined with `edit`.
     *
     * @var \novu\Models\Components\MarkdownReplyContentDto|\novu\Models\Components\CardReplyContentDto|\novu\Models\Components\ToolApprovalCardReplyContentDto|null $reply
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reply')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\MarkdownReplyContentDto|\novu\Models\Components\CardReplyContentDto|\novu\Models\Components\ToolApprovalCardReplyContentDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public MarkdownReplyContentDto|CardReplyContentDto|ToolApprovalCardReplyContentDto|null $reply = null;

    /**
     * Tool-lifecycle ledger row for a gated tool call. Pair with `reply.toolApprovalCard` (or another reply shape) to deliver the approval UI.
     *
     * @var ?\novu\Models\Components\ToolApprovalRequestPayloadDto $toolApprovalRequest
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('toolApprovalRequest')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ToolApprovalRequestPayloadDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ToolApprovalRequestPayloadDto $toolApprovalRequest = null;

    /**
     * In-place edit of a previously posted agent message. Cannot be combined with reply, resolve, signals, toolResults, toolApprovalRequest, addReactions, or deleteMessages.
     *
     * @var ?\novu\Models\Components\EditPayloadDto $edit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('edit')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\EditPayloadDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?EditPayloadDto $edit = null;

    /**
     * Mark the conversation resolved. May be combined with a final `reply`.
     *
     * @var ?\novu\Models\Components\ResolveDto $resolve
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resolve')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ResolveDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ResolveDto $resolve = null;

    /**
     * Side-effect signals executed during this turn: conversation metadata mutations or Novu workflow triggers.
     *
     * @var ?array<\novu\Models\Components\MetadataSetSignalDto|\novu\Models\Components\MetadataDeleteSignalDto|\novu\Models\Components\MetadataClearSignalDto|\novu\Models\Components\TriggerSignalDto> $signals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('signals')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\MetadataSetSignalDto|\novu\Models\Components\MetadataDeleteSignalDto|\novu\Models\Components\MetadataClearSignalDto|\novu\Models\Components\TriggerSignalDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $signals = null;

    /**
     * Tool-call outcomes to persist in conversation history (typically before the assistant reply).
     *
     * @var ?array<\novu\Models\Components\ToolResultDto> $toolResults
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('toolResults')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\ToolResultDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $toolResults = null;

    /**
     * Emoji reactions to add to existing platform messages.
     *
     * @var ?array<\novu\Models\Components\AddReactionPayloadDto> $addReactions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addReactions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\AddReactionPayloadDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $addReactions = null;

    /**
     * Delete previously posted platform messages. Removes the rendered message only — history is preserved.
     *
     * @var ?array<\novu\Models\Components\DeleteMessagePayloadDto> $deleteMessages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deleteMessages')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\DeleteMessagePayloadDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $deleteMessages = null;

    /**
     * Per-turn typing/status control. Pass `{ status?: string }` to set/update the status (omit `status` for "Thinking…"), or `"stop"` to clear it. Best-effort per platform.
     *
     * @var \novu\Models\Components\Typing1|\novu\Models\Components\TypingStatusDto|null $typing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('typing')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Typing1|\novu\Models\Components\TypingStatusDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public Typing1|TypingStatusDto|null $typing = null;

    /**
     * Bridge reports that the customer runtime failed this turn. Cannot be combined with other actions. Novu delivers generic user-facing error copy.
     *
     * @var ?bool $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $error = null;

    /**
     * @param  string  $conversationId
     * @param  string  $integrationIdentifier
     * @param  \novu\Models\Components\MarkdownReplyContentDto|\novu\Models\Components\CardReplyContentDto|\novu\Models\Components\ToolApprovalCardReplyContentDto|null  $reply
     * @param  ?\novu\Models\Components\ToolApprovalRequestPayloadDto  $toolApprovalRequest
     * @param  ?\novu\Models\Components\EditPayloadDto  $edit
     * @param  ?\novu\Models\Components\ResolveDto  $resolve
     * @param  ?array<\novu\Models\Components\MetadataSetSignalDto|\novu\Models\Components\MetadataDeleteSignalDto|\novu\Models\Components\MetadataClearSignalDto|\novu\Models\Components\TriggerSignalDto>  $signals
     * @param  ?array<\novu\Models\Components\ToolResultDto>  $toolResults
     * @param  ?array<\novu\Models\Components\AddReactionPayloadDto>  $addReactions
     * @param  ?array<\novu\Models\Components\DeleteMessagePayloadDto>  $deleteMessages
     * @param  \novu\Models\Components\Typing1|\novu\Models\Components\TypingStatusDto|null  $typing
     * @param  ?bool  $error
     * @phpstan-pure
     */
    public function __construct(string $conversationId, string $integrationIdentifier, MarkdownReplyContentDto|CardReplyContentDto|ToolApprovalCardReplyContentDto|null $reply = null, ?ToolApprovalRequestPayloadDto $toolApprovalRequest = null, ?EditPayloadDto $edit = null, ?ResolveDto $resolve = null, ?array $signals = null, ?array $toolResults = null, ?array $addReactions = null, ?array $deleteMessages = null, Typing1|TypingStatusDto|null $typing = null, ?bool $error = null)
    {
        $this->conversationId = $conversationId;
        $this->integrationIdentifier = $integrationIdentifier;
        $this->reply = $reply;
        $this->toolApprovalRequest = $toolApprovalRequest;
        $this->edit = $edit;
        $this->resolve = $resolve;
        $this->signals = $signals;
        $this->toolResults = $toolResults;
        $this->addReactions = $addReactions;
        $this->deleteMessages = $deleteMessages;
        $this->typing = $typing;
        $this->error = $error;
    }
}