<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class AgentToolDto
{
    /**
     *
     * @var string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalId')]
    public string $externalId;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var \novu\Models\Components\AgentToolDtoType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\AgentToolDtoType')]
    public AgentToolDtoType $type;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * @param  string  $externalId
     * @param  string  $name
     * @param  \novu\Models\Components\AgentToolDtoType  $type
     * @param  ?string  $description
     * @phpstan-pure
     */
    public function __construct(string $externalId, string $name, AgentToolDtoType $type, ?string $description = null)
    {
        $this->externalId = $externalId;
        $this->name = $name;
        $this->type = $type;
        $this->description = $description;
    }
}