<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class AgentIntegrationSummaryDto
{
    /**
     * Integration document id.
     *
     * @var string $integrationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('integrationId')]
    public string $integrationId;

    /**
     *
     * @var string $providerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providerId')]
    public string $providerId;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    public string $identifier;

    /**
     *
     * @var bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    public bool $active;

    /**
     * Channel type through which the message is sent
     *
     * @var ?\novu\Models\Components\ChannelTypeEnum $channel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channel')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ChannelTypeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ChannelTypeEnum $channel = null;

    /**
     * @param  string  $integrationId
     * @param  string  $providerId
     * @param  string  $name
     * @param  string  $identifier
     * @param  bool  $active
     * @param  ?\novu\Models\Components\ChannelTypeEnum  $channel
     * @phpstan-pure
     */
    public function __construct(string $integrationId, string $providerId, string $name, string $identifier, bool $active, ?ChannelTypeEnum $channel = null)
    {
        $this->integrationId = $integrationId;
        $this->providerId = $providerId;
        $this->name = $name;
        $this->identifier = $identifier;
        $this->active = $active;
        $this->channel = $channel;
    }
}