<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class AgentMcpServerDto
{
    /**
     *
     * @var string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalId')]
    public string $externalId;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * @param  string  $externalId
     * @param  string  $name
     * @param  string  $url
     * @phpstan-pure
     */
    public function __construct(string $externalId, string $name, string $url)
    {
        $this->externalId = $externalId;
        $this->name = $name;
        $this->url = $url;
    }
}