<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class BulkUpdateSubscriberPreferenceItemDto
{
    /**
     * Channel-specific preference settings
     *
     * @var PatchPreferenceChannelsDto $channels
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channels')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\PatchPreferenceChannelsDto')]
    public PatchPreferenceChannelsDto $channels;

    /**
     * Workflow internal _id, identifier or slug
     *
     * @var string $workflowId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workflowId')]
    public string $workflowId;

    /**
     * @param  PatchPreferenceChannelsDto  $channels
     * @param  string  $workflowId
     * @phpstan-pure
     */
    public function __construct(PatchPreferenceChannelsDto $channels, string $workflowId)
    {
        $this->channels = $channels;
        $this->workflowId = $workflowId;
    }
}