<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class ChannelSettingsDto
{
    /**
     * The provider identifier for the credentials
     *
     * @var ProviderId $providerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providerId')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ProviderId')]
    public ProviderId $providerId;

    /**
     * Credentials payload for the specified provider
     *
     * @var ChannelCredentials $credentials
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('credentials')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ChannelCredentials')]
    public ChannelCredentials $credentials;

    /**
     * The unique identifier of the integration associated with this channel.
     *
     * @var string $integrationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_integrationId')]
    public string $integrationId;

    /**
     * The integration identifier
     *
     * @var ?string $integrationIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('integrationIdentifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $integrationIdentifier = null;

    /**
     * @param  ProviderId  $providerId
     * @param  ChannelCredentials  $credentials
     * @param  string  $integrationId
     * @param  ?string  $integrationIdentifier
     * @phpstan-pure
     */
    public function __construct(ProviderId $providerId, ChannelCredentials $credentials, string $integrationId, ?string $integrationIdentifier = null)
    {
        $this->providerId = $providerId;
        $this->credentials = $credentials;
        $this->integrationId = $integrationId;
        $this->integrationIdentifier = $integrationIdentifier;
    }
}