<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Type of channel endpoint */
enum CreateWebhookEndpointDtoType: string
{
    case Webhook = 'webhook';
}
