<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class CreateContextRequestDto
{
    /**
     * Context type (e.g., tenant, app, workspace). Must be lowercase alphanumeric with optional separators.
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * Unique identifier for this context. Must be lowercase alphanumeric with optional separators.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Optional custom data to associate with this context.
     *
     * @var ?Data $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Data|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Data $data = null;

    /**
     * @param  string  $type
     * @param  string  $id
     * @param  ?Data  $data
     * @phpstan-pure
     */
    public function __construct(string $type, string $id, ?Data $data = null)
    {
        $this->type = $type;
        $this->id = $id;
        $this->data = $data;
    }
}