<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Data - Additional custom data for the subscriber */
class Data
{

    public function __construct()
    {
    }
}