<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class DeleteMessageResponseDto
{
    /**
     * A boolean stating the success of the action
     *
     * @var bool $acknowledged
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('acknowledged')]
    public bool $acknowledged;

    /**
     * The status enum for the performed action
     *
     * @var DeleteMessageResponseDtoStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\DeleteMessageResponseDtoStatus')]
    public DeleteMessageResponseDtoStatus $status;

    /**
     * @param  bool  $acknowledged
     * @param  DeleteMessageResponseDtoStatus  $status
     */
    public function __construct(bool $acknowledged, DeleteMessageResponseDtoStatus $status)
    {
        $this->acknowledged = $acknowledged;
        $this->status = $status;
    }
}