<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class DigestTimedConfigDto
{
    /**
     * Time at which the digest is triggered
     *
     * @var ?string $atTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('atTime')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $atTime = null;

    /**
     * Days of the week for the digest
     *
     * @var ?array<DigestTimedConfigDtoWeekDays> $weekDays
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('weekDays')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\DigestTimedConfigDtoWeekDays>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $weekDays = null;

    /**
     * Specific days of the month for the digest
     *
     * @var ?array<float> $monthDays
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('monthDays')]
    #[\Speakeasy\Serializer\Annotation\Type('array<float>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $monthDays = null;

    /**
     * Ordinal position for the digest
     *
     * @var ?OrdinalEnum $ordinal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ordinal')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\OrdinalEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrdinalEnum $ordinal = null;

    /**
     * Value of the ordinal
     *
     * @var ?OrdinalValueEnum $ordinalValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ordinalValue')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\OrdinalValueEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrdinalValueEnum $ordinalValue = null;

    /**
     * Type of monthly schedule
     *
     * @var ?MonthlyTypeEnum $monthlyType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('monthlyType')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\MonthlyTypeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MonthlyTypeEnum $monthlyType = null;

    /**
     * Cron expression for scheduling
     *
     * @var ?string $cronExpression
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cronExpression')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cronExpression = null;

    /**
     * @param  ?string  $atTime
     * @param  ?array<DigestTimedConfigDtoWeekDays>  $weekDays
     * @param  ?array<float>  $monthDays
     * @param  ?OrdinalEnum  $ordinal
     * @param  ?OrdinalValueEnum  $ordinalValue
     * @param  ?MonthlyTypeEnum  $monthlyType
     * @param  ?string  $cronExpression
     * @phpstan-pure
     */
    public function __construct(?string $atTime = null, ?array $weekDays = null, ?array $monthDays = null, ?OrdinalEnum $ordinal = null, ?OrdinalValueEnum $ordinalValue = null, ?MonthlyTypeEnum $monthlyType = null, ?string $cronExpression = null)
    {
        $this->atTime = $atTime;
        $this->weekDays = $weekDays;
        $this->monthDays = $monthDays;
        $this->ordinal = $ordinal;
        $this->ordinalValue = $ordinalValue;
        $this->monthlyType = $monthlyType;
        $this->cronExpression = $cronExpression;
    }
}