<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class DomainConnectStatusResponseDto
{
    /**
     *
     * @var bool $available
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('available')]
    public bool $available;

    /**
     * $manualRecords
     *
     * @var array<\novu\Models\Components\ExpectedDnsRecordDto> $manualRecords
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('manualRecords')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\ExpectedDnsRecordDto>')]
    public array $manualRecords;

    /**
     *
     * @var ?string $providerName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providerName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $providerName = null;

    /**
     *
     * @var ?string $providerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providerId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $providerId = null;

    /**
     *
     * @var ?string $reason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reason')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reason = null;

    /**
     *
     * @var ?\novu\Models\Components\ReasonCode $reasonCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reasonCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ReasonCode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ReasonCode $reasonCode = null;

    /**
     * @param  bool  $available
     * @param  array<\novu\Models\Components\ExpectedDnsRecordDto>  $manualRecords
     * @param  ?string  $providerName
     * @param  ?string  $providerId
     * @param  ?string  $reason
     * @param  ?\novu\Models\Components\ReasonCode  $reasonCode
     * @phpstan-pure
     */
    public function __construct(bool $available, array $manualRecords, ?string $providerName = null, ?string $providerId = null, ?string $reason = null, ?ReasonCode $reasonCode = null)
    {
        $this->available = $available;
        $this->manualRecords = $manualRecords;
        $this->providerName = $providerName;
        $this->providerId = $providerId;
        $this->reason = $reason;
        $this->reasonCode = $reasonCode;
    }
}