<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class DomainResponseDto
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var \novu\Models\Components\DomainResponseDtoStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\DomainResponseDtoStatus')]
    public DomainResponseDtoStatus $status;

    /**
     *
     * @var bool $mxRecordConfigured
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mxRecordConfigured')]
    public bool $mxRecordConfigured;

    /**
     *
     * @var string $environmentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_environmentId')]
    public string $environmentId;

    /**
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_organizationId')]
    public string $organizationId;

    /**
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     *
     * @var string $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public string $updatedAt;

    /**
     *
     * @var ?string $dnsProvider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dnsProvider')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dnsProvider = null;

    /**
     * $expectedDnsRecords
     *
     * @var ?array<\novu\Models\Components\ExpectedDnsRecordDto> $expectedDnsRecords
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expectedDnsRecords')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\ExpectedDnsRecordDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $expectedDnsRecords = null;

    /**
     * String key-value metadata (max 10 keys, 500 characters total when set via API).
     *
     * @var ?array<string, string> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $data = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  \novu\Models\Components\DomainResponseDtoStatus  $status
     * @param  bool  $mxRecordConfigured
     * @param  string  $environmentId
     * @param  string  $organizationId
     * @param  string  $createdAt
     * @param  string  $updatedAt
     * @param  ?string  $dnsProvider
     * @param  ?array<\novu\Models\Components\ExpectedDnsRecordDto>  $expectedDnsRecords
     * @param  ?array<string, string>  $data
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, DomainResponseDtoStatus $status, bool $mxRecordConfigured, string $environmentId, string $organizationId, string $createdAt, string $updatedAt, ?string $dnsProvider = null, ?array $expectedDnsRecords = null, ?array $data = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->status = $status;
        $this->mxRecordConfigured = $mxRecordConfigured;
        $this->environmentId = $environmentId;
        $this->organizationId = $organizationId;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->dnsProvider = $dnsProvider;
        $this->expectedDnsRecords = $expectedDnsRecords;
        $this->data = $data;
    }
}