<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Editor type of the layout. */
enum EditorType: string
{
    case Html = 'html';
    case Block = 'block';
}
