<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class EmailLayoutRenderOutput
{
    /**
     * Content of the email
     *
     * @var string $body
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('body')]
    public string $body;

    /**
     * @param  string  $body
     * @phpstan-pure
     */
    public function __construct(string $body)
    {
        $this->body = $body;
    }
}