<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class GeneratePreviewResponseDto
{
    /**
     * Preview payload example
     *
     * @var \novu\Models\Components\PreviewPayloadDto $previewPayloadExample
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('previewPayloadExample')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\PreviewPayloadDto')]
    public PreviewPayloadDto $previewPayloadExample;

    /**
     * Preview result
     *
     * @var array<string, mixed>|\novu\Models\Components\Result2|\novu\Models\Components\Three|\novu\Models\Components\Result4|\novu\Models\Components\Result5|\novu\Models\Components\Six|\novu\Models\Components\Seven|\novu\Models\Components\Eight|\novu\Models\Components\Nine $result
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('result')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|\novu\Models\Components\Result2|\novu\Models\Components\Three|\novu\Models\Components\Result4|\novu\Models\Components\Result5|\novu\Models\Components\Six|\novu\Models\Components\Seven|\novu\Models\Components\Eight|\novu\Models\Components\Nine')]
    public array|Result2|Three|Result4|Result5|Six|Seven|Eight|Nine $result;

    /**
     * Sample novu-signature header value for HTTP request steps
     *
     * @var ?string $novuSignature
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('novuSignature')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $novuSignature = null;

    /**
     * The payload schema that was used to generate the preview payload example
     *
     * @var ?array<string, mixed> $schema
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('schema')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $schema = null;

    /**
     * @param  \novu\Models\Components\PreviewPayloadDto  $previewPayloadExample
     * @param  array<string, mixed>|\novu\Models\Components\Result2|\novu\Models\Components\Three|\novu\Models\Components\Result4|\novu\Models\Components\Result5|\novu\Models\Components\Six|\novu\Models\Components\Seven|\novu\Models\Components\Eight|\novu\Models\Components\Nine  $result
     * @param  ?string  $novuSignature
     * @param  ?array<string, mixed>  $schema
     * @phpstan-pure
     */
    public function __construct(PreviewPayloadDto $previewPayloadExample, array|Result2|Three|Result4|Result5|Six|Seven|Eight|Nine $result, ?string $novuSignature = null, ?array $schema = null)
    {
        $this->previewPayloadExample = $previewPayloadExample;
        $this->result = $result;
        $this->novuSignature = $novuSignature;
        $this->schema = $schema;
    }
}