<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class GenerateConnectOauthUrlRequestDto
{
    /**
     * Integration identifier
     *
     * @var string $integrationIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('integrationIdentifier')]
    public string $integrationIdentifier;

    /**
     * The subscriber ID to associate with the channel connection. For Slack: optional for workspace connections (required only for incoming-webhook scope). For MS Teams: optional. Admin consent is tenant-wide.
     *
     * @var ?string $subscriberId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscriberId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subscriberId = null;

    /**
     * Identifier of the channel connection that will be created. Generated automatically if not provided.
     *
     * @var ?string $connectionIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connectionIdentifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connectionIdentifier = null;

    /**
     * $context
     *
     * @var ?array<string, string|\novu\Models\Components\GenerateConnectOauthUrlRequestDtoContext2> $context
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('context')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string|\novu\Models\Components\GenerateConnectOauthUrlRequestDtoContext2>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $context = null;

    /**
     * **Slack only**: OAuth scopes to request during authorization. If not specified, default scopes will be used: chat:write, chat:write.public, channels:read, groups:read, users:read, users:read.email. **MS Teams**: ignored — uses admin consent with pre-configured Azure AD permissions.
     *
     * @var ?array<string> $scope
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scope')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $scope = null;

    /**
     * Connection mode that determines how the channel connection is scoped. "subscriber" (default) associates the connection with a specific subscriber. "shared" associates the connection with a context instead of a subscriber.
     *
     * @var ?\novu\Models\Components\GenerateConnectOauthUrlRequestDtoConnectionMode $connectionMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connectionMode')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\GenerateConnectOauthUrlRequestDtoConnectionMode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GenerateConnectOauthUrlRequestDtoConnectionMode $connectionMode = null;

    /**
     * When true (default when connectionMode is "subscriber"), after the workspace/tenant connection is created the OAuth flow also links the subscriber who clicked "Connect" as a personal endpoint. For Slack, uses the authed_user.id returned by oauth.v2.access — no extra redirect. For MS Teams, triggers a second OAuth redirect for delegated user-identity consent. Set to false to only create the workspace connection without linking the individual user.
     *
     * @var ?bool $autoLinkUser
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('autoLinkUser')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $autoLinkUser = null;

    /**
     * @param  string  $integrationIdentifier
     * @param  ?string  $subscriberId
     * @param  ?string  $connectionIdentifier
     * @param  ?array<string, string|\novu\Models\Components\GenerateConnectOauthUrlRequestDtoContext2>  $context
     * @param  ?array<string>  $scope
     * @param  ?\novu\Models\Components\GenerateConnectOauthUrlRequestDtoConnectionMode  $connectionMode
     * @param  ?bool  $autoLinkUser
     * @phpstan-pure
     */
    public function __construct(string $integrationIdentifier, ?string $subscriberId = null, ?string $connectionIdentifier = null, ?array $context = null, ?array $scope = null, ?GenerateConnectOauthUrlRequestDtoConnectionMode $connectionMode = null, ?bool $autoLinkUser = null)
    {
        $this->integrationIdentifier = $integrationIdentifier;
        $this->subscriberId = $subscriberId;
        $this->connectionIdentifier = $connectionIdentifier;
        $this->context = $context;
        $this->scope = $scope;
        $this->connectionMode = $connectionMode;
        $this->autoLinkUser = $autoLinkUser;
    }
}