<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class GeneratePreviewRequestDto
{
    /**
     * Optional control values
     *
     * @var ?array<string, mixed> $controlValues
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('controlValues')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $controlValues = null;

    /**
     * Optional payload for preview generation
     *
     * @var ?\novu\Models\Components\PreviewPayloadDto $previewPayload
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('previewPayload')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\PreviewPayloadDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PreviewPayloadDto $previewPayload = null;

    /**
     * @param  ?array<string, mixed>  $controlValues
     * @param  ?\novu\Models\Components\PreviewPayloadDto  $previewPayload
     * @phpstan-pure
     */
    public function __construct(?array $controlValues = null, ?PreviewPayloadDto $previewPayload = null)
    {
        $this->controlValues = $controlValues;
        $this->previewPayload = $previewPayload;
    }
}