<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class GetEnvironmentVariableUsageResponseDto
{
    /**
     * Array of workflows that reference this environment variable
     *
     * @var array<\novu\Models\Components\EnvironmentVariableWorkflowInfoDto> $workflows
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workflows')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\EnvironmentVariableWorkflowInfoDto>')]
    public array $workflows;

    /**
     * @param  array<\novu\Models\Components\EnvironmentVariableWorkflowInfoDto>  $workflows
     * @phpstan-pure
     */
    public function __construct(array $workflows)
    {
        $this->workflows = $workflows;
    }
}