<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class GetPreferencesResponseDto
{
    /**
     * The level of the preference (global or template)
     *
     * @var PreferenceLevelEnum $level
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('level')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\PreferenceLevelEnum')]
    public PreferenceLevelEnum $level;

    /**
     * Whether the preference is enabled
     *
     * @var bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    public bool $enabled;

    /**
     * Channel-specific preference settings
     *
     * @var SubscriberPreferenceChannels $channels
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channels')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\SubscriberPreferenceChannels')]
    public SubscriberPreferenceChannels $channels;

    /**
     * Workflow information if this is a template-level preference
     *
     * @var ?Workflow $workflow
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workflow')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Workflow|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Workflow $workflow = null;

    /**
     * Condition using JSON Logic rules
     *
     * @var ?Condition $condition
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('condition')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Condition|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Condition $condition = null;

    /**
     * @param  PreferenceLevelEnum  $level
     * @param  bool  $enabled
     * @param  SubscriberPreferenceChannels  $channels
     * @param  ?Workflow  $workflow
     * @param  ?Condition  $condition
     * @phpstan-pure
     */
    public function __construct(PreferenceLevelEnum $level, bool $enabled, SubscriberPreferenceChannels $channels, ?Workflow $workflow = null, ?Condition $condition = null)
    {
        $this->level = $level;
        $this->enabled = $enabled;
        $this->channels = $channels;
        $this->workflow = $workflow;
        $this->condition = $condition;
    }
}