<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class GetSubscriberPreferencesResponseDto
{
    /**
     * The preferences of the subscriber regarding the related workflow
     *
     * @var Preference $preference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('preference')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Preference')]
    public Preference $preference;

    /**
     * The workflow information and if it is critical or not
     *
     * @var ?TemplateResponse $template
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('template')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\TemplateResponse|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TemplateResponse $template = null;

    /**
     * @param  Preference  $preference
     * @param  ?TemplateResponse  $template
     */
    public function __construct(Preference $preference, ?TemplateResponse $template = null)
    {
        $this->preference = $preference;
        $this->template = $template;
    }
}