<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class HttpRequestControlDto
{
    /**
     * HTTP method
     *
     * @var \novu\Models\Components\HttpMethodEnum $method
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('method')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\HttpMethodEnum')]
    public HttpMethodEnum $method;

    /**
     * Target URL for the HTTP request
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * Request headers as key-value pairs
     *
     * @var ?array<\novu\Models\Components\HttpRequestKeyValuePairDto> $headers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('headers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\HttpRequestKeyValuePairDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $headers = null;

    /**
     * Request body as a raw JSON string. Key-value arrays are supported for legacy workflows.
     *
     * @var string|array<\novu\Models\Components\HttpRequestKeyValuePairDto>|null $body
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('body')]
    #[\Speakeasy\Serializer\Annotation\Type('string|array<\novu\Models\Components\HttpRequestKeyValuePairDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|array|null $body = null;

    /**
     * JSON schema to validate response body against
     *
     * @var ?array<string, mixed> $responseBodySchema
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('responseBodySchema')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $responseBodySchema = null;

    /**
     * Whether to enforce response body schema validation
     *
     * @var ?bool $enforceSchemaValidation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enforceSchemaValidation')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enforceSchemaValidation = null;

    /**
     * Whether to continue workflow execution on failure
     *
     * @var ?bool $continueOnFailure
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('continueOnFailure')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $continueOnFailure = null;

    /**
     * @param  \novu\Models\Components\HttpMethodEnum  $method
     * @param  string  $url
     * @param  ?array<\novu\Models\Components\HttpRequestKeyValuePairDto>  $headers
     * @param  string|array<\novu\Models\Components\HttpRequestKeyValuePairDto>|null  $body
     * @param  ?array<string, mixed>  $responseBodySchema
     * @param  ?bool  $enforceSchemaValidation
     * @param  ?bool  $continueOnFailure
     * @phpstan-pure
     */
    public function __construct(HttpMethodEnum $method, string $url, string|array|null $body = null, ?array $responseBodySchema = null, ?bool $enforceSchemaValidation = null, ?bool $continueOnFailure = null, ?array $headers = null)
    {
        $this->method = $method;
        $this->url = $url;
        $this->headers = $headers;
        $this->body = $body;
        $this->responseBodySchema = $responseBodySchema;
        $this->enforceSchemaValidation = $enforceSchemaValidation;
        $this->continueOnFailure = $continueOnFailure;
    }
}