<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class InBoundParseDomainDto
{
    /**
     *
     * @var ?string $inboundParseDomain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('inboundParseDomain')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $inboundParseDomain = null;

    /**
     * @param  ?string  $inboundParseDomain
     * @phpstan-pure
     */
    public function __construct(?string $inboundParseDomain = null)
    {
        $this->inboundParseDomain = $inboundParseDomain;
    }
}