<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Integration - The updated configurations after auto-configuration */
class Integration
{

    public function __construct()
    {
    }
}