<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Issues - Step issues */
class Issues
{

    public function __construct()
    {
    }
}