<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class LinkChannelEndpointRequestDto
{
    /**
     * Integration identifier for the chat provider integration
     *
     * @var string $integrationIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('integrationIdentifier')]
    public string $integrationIdentifier;

    /**
     * External subscriber identifier to link to their chat identity
     *
     * @var string $subscriberId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscriberId')]
    public string $subscriberId;

    /**
     * @param  string  $integrationIdentifier
     * @param  string  $subscriberId
     * @phpstan-pure
     */
    public function __construct(string $integrationIdentifier, string $subscriberId)
    {
        $this->integrationIdentifier = $integrationIdentifier;
        $this->subscriberId = $subscriberId;
    }
}