<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class LookBackWindowDto
{
    /**
     * Amount of time for the look-back window.
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     * Unit of time for the look-back window.
     *
     * @var LookBackWindowDtoUnit $unit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\LookBackWindowDtoUnit')]
    public LookBackWindowDtoUnit $unit;

    /**
     * @param  float  $amount
     * @param  LookBackWindowDtoUnit  $unit
     * @phpstan-pure
     */
    public function __construct(float $amount, LookBackWindowDtoUnit $unit)
    {
        $this->amount = $amount;
        $this->unit = $unit;
    }
}