<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** MarkMessageActionAsSeenDtoPayload - Message action payload */
class MarkMessageActionAsSeenDtoPayload
{

    public function __construct()
    {
    }
}