<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class MessageActionResult
{
    /**
     * Payload of the action result
     *
     * @var ?MessageActionResultPayload $payload
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payload')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\MessageActionResultPayload|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MessageActionResultPayload $payload = null;

    /**
     * Type of button for the action result
     *
     * @var ?ButtonTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ButtonTypeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ButtonTypeEnum $type = null;

    /**
     * @param  ?MessageActionResultPayload  $payload
     * @param  ?ButtonTypeEnum  $type
     */
    public function __construct(?MessageActionResultPayload $payload = null, ?ButtonTypeEnum $type = null)
    {
        $this->payload = $payload;
        $this->type = $type;
    }
}