<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class MetaDto
{
    /**
     * The total count of subscriber IDs provided
     *
     * @var float $totalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalCount')]
    public float $totalCount;

    /**
     * The count of successfully created subscriptions
     *
     * @var float $successful
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('successful')]
    public float $successful;

    /**
     * The count of failed subscription attempts
     *
     * @var float $failed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failed')]
    public float $failed;

    /**
     * @param  float  $totalCount
     * @param  float  $successful
     * @param  float  $failed
     * @phpstan-pure
     */
    public function __construct(float $totalCount, float $successful, float $failed)
    {
        $this->totalCount = $totalCount;
        $this->successful = $successful;
        $this->failed = $failed;
    }
}