<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Type of monthly schedule */
enum MonthlyTypeEnum: string
{
    case Each = 'each';
    case On = 'on';
}
