<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Opsgenie account region that determines the alert API data-center endpoint. */
enum OpsgenieIntegrationEndpointDtoRegion: string
{
    case Us = 'us';
    case Eu = 'eu';
}
