<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class Overrides
{
    /**
     * The channel type which is overridden
     *
     * @var Channel $channel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channel')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Channel')]
    public Channel $channel;

    /**
     * The source of overrides
     *
     * @var Source $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Source')]
    public Source $source;

    /**
     * @param  Channel  $channel
     * @param  Source  $source
     * @phpstan-pure
     */
    public function __construct(Channel $channel, Source $source)
    {
        $this->channel = $channel;
        $this->source = $source;
    }
}