<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Overrides - This could be used to override provider specific configurations */
class Overrides
{

    public function __construct()
    {
    }
}