<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** PushStepUpsertDtoControlValues - Control values for the Push step */
class PushStepUpsertDtoControlValues
{
    /**
     * JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
     *
     * @var ?array<string, mixed> $skip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('skip')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $skip = null;

    /**
     * Subject/title of the push notification.
     *
     * @var ?string $subject
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subject')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subject = null;

    /**
     * Body content of the push notification.
     *
     * @var ?string $body
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('body')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $body = null;

    /**
     * @param  ?array<string, mixed>  $skip
     * @param  ?string  $subject
     * @param  ?string  $body
     * @phpstan-pure
     */
    public function __construct(?array $skip = null, ?string $subject = null, ?string $body = null)
    {
        $this->skip = $skip;
        $this->subject = $subject;
        $this->body = $body;
    }
}