<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class RenameTopicRequestDto
{
    /**
     * User defined custom name and provided by the user to rename the topic.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * @param  string  $name
     * @phpstan-pure
     */
    public function __construct(string $name)
    {
        $this->name = $name;
    }
}