<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class RequestLogResponseDto
{
    /**
     * Request log identifier
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Creation timestamp
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * Request URL
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * URL pattern
     *
     * @var string $urlPattern
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('urlPattern')]
    public string $urlPattern;

    /**
     * HTTP method
     *
     * @var string $method
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('method')]
    public string $method;

    /**
     * HTTP status code
     *
     * @var float $statusCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('statusCode')]
    public float $statusCode;

    /**
     * Request path
     *
     * @var string $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    public string $path;

    /**
     * Request hostname
     *
     * @var string $hostname
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hostname')]
    public string $hostname;

    /**
     * Client IP address
     *
     * @var string $ip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ip')]
    public string $ip;

    /**
     * User agent string
     *
     * @var string $userAgent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('userAgent')]
    public string $userAgent;

    /**
     * Request body
     *
     * @var string $requestBody
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requestBody')]
    public string $requestBody;

    /**
     * Response body
     *
     * @var string $responseBody
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('responseBody')]
    public string $responseBody;

    /**
     * User identifier
     *
     * @var string $userId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('userId')]
    public string $userId;

    /**
     * Organization identifier
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organizationId')]
    public string $organizationId;

    /**
     * Environment identifier
     *
     * @var string $environmentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('environmentId')]
    public string $environmentId;

    /**
     * Authentication type
     *
     * @var string $authType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authType')]
    public string $authType;

    /**
     * Request duration in milliseconds
     *
     * @var float $durationMs
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('durationMs')]
    public float $durationMs;

    /**
     * Transaction identifier
     *
     * @var ?TransactionId $transactionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transactionId')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\TransactionId|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionId $transactionId = null;

    /**
     * @param  string  $id
     * @param  string  $createdAt
     * @param  string  $url
     * @param  string  $urlPattern
     * @param  string  $method
     * @param  float  $statusCode
     * @param  string  $path
     * @param  string  $hostname
     * @param  string  $ip
     * @param  string  $userAgent
     * @param  string  $requestBody
     * @param  string  $responseBody
     * @param  string  $userId
     * @param  string  $organizationId
     * @param  string  $environmentId
     * @param  string  $authType
     * @param  float  $durationMs
     * @param  ?TransactionId  $transactionId
     * @phpstan-pure
     */
    public function __construct(string $id, string $createdAt, string $url, string $urlPattern, string $method, float $statusCode, string $path, string $hostname, string $ip, string $userAgent, string $requestBody, string $responseBody, string $userId, string $organizationId, string $environmentId, string $authType, float $durationMs, ?TransactionId $transactionId = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->url = $url;
        $this->urlPattern = $urlPattern;
        $this->method = $method;
        $this->statusCode = $statusCode;
        $this->path = $path;
        $this->hostname = $hostname;
        $this->ip = $ip;
        $this->userAgent = $userAgent;
        $this->requestBody = $requestBody;
        $this->responseBody = $responseBody;
        $this->userId = $userId;
        $this->organizationId = $organizationId;
        $this->environmentId = $environmentId;
        $this->authType = $authType;
        $this->durationMs = $durationMs;
        $this->transactionId = $transactionId;
    }
}