<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class ResolveDto
{
    /**
     * Optional human-readable resolution summary stored on the conversation.
     *
     * @var ?string $summary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('summary')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $summary = null;

    /**
     * @param  ?string  $summary
     * @phpstan-pure
     */
    public function __construct(?string $summary = null)
    {
        $this->summary = $summary;
    }
}