<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** The resource type to associate translation with */
enum ResourceType: string
{
    case Workflow = 'workflow';
}
