<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class Result5
{
    /**
     *
     * @var ?\novu\Models\Components\GeneratePreviewResponseDtoResult5Type $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\GeneratePreviewResponseDtoResult5Type|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GeneratePreviewResponseDtoResult5Type $type = null;

    /**
     *
     * @var ?\novu\Models\Components\SmsRenderOutput $preview
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('preview')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\SmsRenderOutput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SmsRenderOutput $preview = null;

    /**
     *
     * @var ?\novu\Models\Components\PreviewErrorDto $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\PreviewErrorDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PreviewErrorDto $error = null;

    /**
     * @param  ?\novu\Models\Components\GeneratePreviewResponseDtoResult5Type  $type
     * @param  ?\novu\Models\Components\SmsRenderOutput  $preview
     * @param  ?\novu\Models\Components\PreviewErrorDto  $error
     * @phpstan-pure
     */
    public function __construct(?GeneratePreviewResponseDtoResult5Type $type = null, ?SmsRenderOutput $preview = null, ?PreviewErrorDto $error = null)
    {
        $this->type = $type;
        $this->preview = $preview;
        $this->error = $error;
    }
}