<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Severity of the workflow */
enum SeverityLevelEnum: string
{
    case High = 'high';
    case Medium = 'medium';
    case Low = 'low';
    case None = 'none';
}
