<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Status of the event */
enum Status: string
{
    case Opened = 'opened';
    case Rejected = 'rejected';
    case Sent = 'sent';
    case Deferred = 'deferred';
    case Delivered = 'delivered';
    case Bounced = 'bounced';
    case Dropped = 'dropped';
    case Clicked = 'clicked';
    case Blocked = 'blocked';
    case Spam = 'spam';
    case Unsubscribed = 'unsubscribed';
    case Delayed = 'delayed';
    case Complaint = 'complaint';
    case Created = 'created';
    case Accepted = 'accepted';
    case Queued = 'queued';
    case Sending = 'sending';
    case Failed = 'failed';
    case Undelivered = 'undelivered';
    case Dismissed = 'dismissed';
}
