<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class StepFilterDto
{
    /**
     *
     * @var bool $isNegated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isNegated')]
    public bool $isNegated;

    /**
     *
     * @var \novu\Models\Components\BuilderFieldTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\BuilderFieldTypeEnum')]
    public BuilderFieldTypeEnum $type;

    /**
     *
     * @var \novu\Models\Components\StepFilterDtoValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\StepFilterDtoValue')]
    public StepFilterDtoValue $value;

    /**
     * $children
     *
     * @var array<\novu\Models\Components\FieldFilterPartDto> $children
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('children')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\FieldFilterPartDto>')]
    public array $children;

    /**
     * @param  bool  $isNegated
     * @param  \novu\Models\Components\BuilderFieldTypeEnum  $type
     * @param  \novu\Models\Components\StepFilterDtoValue  $value
     * @param  array<\novu\Models\Components\FieldFilterPartDto>  $children
     * @phpstan-pure
     */
    public function __construct(bool $isNegated, BuilderFieldTypeEnum $type, StepFilterDtoValue $value, array $children)
    {
        $this->isNegated = $isNegated;
        $this->type = $type;
        $this->value = $value;
        $this->children = $children;
    }
}