<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class StepsOverrides
{
    /**
     * Passing the provider id and the provider specific configurations
     *
     * @var ?array<string, array<string, mixed>> $providers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, array<string, mixed>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $providers = null;

    /**
     * Override the or remove the layout for this specific step
     *
     * @var ?string $layoutId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('layoutId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $layoutId = null;

    /**
     * @param  ?array<string, array<string, mixed>>  $providers
     * @param  ?string  $layoutId
     * @phpstan-pure
     */
    public function __construct(?array $providers = null, ?string $layoutId = null)
    {
        $this->providers = $providers;
        $this->layoutId = $layoutId;
    }
}