<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class StepIssuesDto
{
    /**
     * Controls-related issues
     *
     * @var ?array<string, array<StepContentIssueDto>> $controls
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('controls')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, array<\novu\Models\Components\StepContentIssueDto>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $controls = null;

    /**
     * Integration-related issues
     *
     * @var ?array<string, array<StepIntegrationIssue>> $integration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('integration')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, array<\novu\Models\Components\StepIntegrationIssue>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $integration = null;

    /**
     * @param  ?array<string, array<StepContentIssueDto>>  $controls
     * @param  ?array<string, array<StepIntegrationIssue>>  $integration
     * @phpstan-pure
     */
    public function __construct(?array $controls = null, ?array $integration = null)
    {
        $this->controls = $controls;
        $this->integration = $integration;
    }
}