<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class StepContentIssueDto
{
    /**
     * Type of step content issue
     *
     * @var \novu\Models\Components\ContentIssueEnum $issueType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issueType')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ContentIssueEnum')]
    public ContentIssueEnum $issueType;

    /**
     * Detailed message describing the issue
     *
     * @var string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     * Name of the variable related to the issue
     *
     * @var ?string $variableName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variableName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $variableName = null;

    /**
     * Blocking severity of the issue. `error` (default when omitted) blocks save; `warning` is a non-blocking notice.
     *
     * @var ?\novu\Models\Components\StepIssueSeverityEnum $severity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('severity')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\StepIssueSeverityEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?StepIssueSeverityEnum $severity = null;

    /**
     * @param  \novu\Models\Components\ContentIssueEnum  $issueType
     * @param  string  $message
     * @param  ?string  $variableName
     * @param  ?\novu\Models\Components\StepIssueSeverityEnum  $severity
     * @phpstan-pure
     */
    public function __construct(ContentIssueEnum $issueType, string $message, ?string $variableName = null, ?StepIssueSeverityEnum $severity = null)
    {
        $this->issueType = $issueType;
        $this->message = $message;
        $this->variableName = $variableName;
        $this->severity = $severity;
    }
}