<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class SubscriptionResponseDto
{
    /**
     * The unique identifier of the subscription
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_id')]
    public string $id;

    /**
     * The topic information
     *
     * @var TopicDto $topic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('topic')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\TopicDto')]
    public TopicDto $topic;

    /**
     * The creation date of the subscription
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * The last update date of the subscription
     *
     * @var string $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public string $updatedAt;

    /**
     * The identifier of the subscription
     *
     * @var ?string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     * The name of the subscription
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The subscriber information
     *
     * @var ?Subscriber $subscriber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscriber')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\Subscriber|null')]
    public ?Subscriber $subscriber;

    /**
     * The preferences for workflows in this subscription
     *
     * @var ?array<SubscriptionPreferenceDto> $preferences
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('preferences')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\SubscriptionPreferenceDto>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $preferences = null;

    /**
     * @param  string  $id
     * @param  TopicDto  $topic
     * @param  string  $createdAt
     * @param  string  $updatedAt
     * @param  ?string  $identifier
     * @param  ?string  $name
     * @param  ?Subscriber  $subscriber
     * @param  ?array<SubscriptionPreferenceDto>  $preferences
     * @phpstan-pure
     */
    public function __construct(string $id, TopicDto $topic, string $createdAt, string $updatedAt, ?string $identifier = null, ?string $name = null, ?Subscriber $subscriber = null, ?array $preferences = null)
    {
        $this->id = $id;
        $this->topic = $topic;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->identifier = $identifier;
        $this->name = $name;
        $this->subscriber = $subscriber;
        $this->preferences = $preferences;
    }
}