<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** SubscriptionPreferenceDtoData - Custom data associated with the workflow */
class SubscriptionPreferenceDtoData
{

    public function __construct()
    {
    }
}