<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class SubscriberChannelDto
{
    /**
     * The ID of the chat or push provider.
     *
     * @var ProviderId $providerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providerId')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ProviderId')]
    public ProviderId $providerId;

    /**
     * Credentials for the channel.
     *
     * @var ChannelCredentialsDto $credentials
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('credentials')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ChannelCredentialsDto')]
    public ChannelCredentialsDto $credentials;

    /**
     * An optional identifier for the integration.
     *
     * @var ?string $integrationIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('integrationIdentifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $integrationIdentifier = null;

    /**
     * @param  ProviderId  $providerId
     * @param  ChannelCredentialsDto  $credentials
     * @param  ?string  $integrationIdentifier
     */
    public function __construct(ProviderId $providerId, ChannelCredentialsDto $credentials, ?string $integrationIdentifier = null)
    {
        $this->providerId = $providerId;
        $this->credentials = $credentials;
        $this->integrationIdentifier = $integrationIdentifier;
    }
}