<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class SyncResultDto
{
    /**
     * Type of the layout
     *
     * @var ResourceTypeEnum $resourceType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resourceType')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ResourceTypeEnum')]
    public ResourceTypeEnum $resourceType;

    /**
     * Successfully synced resources
     *
     * @var array<SyncedWorkflowDto> $successful
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('successful')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\SyncedWorkflowDto>')]
    public array $successful;

    /**
     * Failed resource syncs
     *
     * @var array<FailedWorkflowDto> $failed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failed')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\FailedWorkflowDto>')]
    public array $failed;

    /**
     * Skipped resources
     *
     * @var array<SkippedWorkflowDto> $skipped
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('skipped')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\novu\Models\Components\SkippedWorkflowDto>')]
    public array $skipped;

    /**
     * Total number of resources processed
     *
     * @var float $totalProcessed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalProcessed')]
    public float $totalProcessed;

    /**
     * @param  ResourceTypeEnum  $resourceType
     * @param  array<SyncedWorkflowDto>  $successful
     * @param  array<FailedWorkflowDto>  $failed
     * @param  array<SkippedWorkflowDto>  $skipped
     * @param  float  $totalProcessed
     * @phpstan-pure
     */
    public function __construct(ResourceTypeEnum $resourceType, array $successful, array $failed, array $skipped, float $totalProcessed)
    {
        $this->resourceType = $resourceType;
        $this->successful = $successful;
        $this->failed = $failed;
        $this->skipped = $skipped;
        $this->totalProcessed = $totalProcessed;
    }
}