<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Target attribute for the redirect link */
enum Target: string
{
    case Self = '_self';
    case Blank = '_blank';
    case Parent = '_parent';
    case Top = '_top';
    case UnfencedTop = '_unfencedTop';
}
