<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class TestDomainRouteResponseDto
{
    /**
     *
     * @var bool $matched
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('matched')]
    public bool $matched;

    /**
     *
     * @var bool $dryRun
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dryRun')]
    public bool $dryRun;

    /**
     *
     * @var ?\novu\Models\Components\DomainStatus $domainStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domainStatus')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\DomainStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DomainStatus $domainStatus = null;

    /**
     *
     * @var ?bool $mxRecordConfigured
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mxRecordConfigured')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mxRecordConfigured = null;

    /**
     *
     * @var ?\novu\Models\Components\TestDomainRouteResponseDtoType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\TestDomainRouteResponseDtoType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TestDomainRouteResponseDtoType $type = null;

    /**
     * Human-readable delivery target summary in dry-run mode.
     *
     * @var ?string $wouldDeliverTo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wouldDeliverTo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $wouldDeliverTo = null;

    /**
     * The outbound payload (dry-run only).
     *
     * @var ?array<string, mixed> $payload
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payload')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $payload = null;

    /**
     *
     * @var ?\novu\Models\Components\TestDomainRouteWebhookResultDto $webhook
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('webhook')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\TestDomainRouteWebhookResultDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TestDomainRouteWebhookResultDto $webhook = null;

    /**
     *
     * @var ?\novu\Models\Components\TestDomainRouteAgentResultDto $agent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('agent')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\TestDomainRouteAgentResultDto|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TestDomainRouteAgentResultDto $agent = null;

    /**
     * @param  bool  $matched
     * @param  bool  $dryRun
     * @param  ?\novu\Models\Components\DomainStatus  $domainStatus
     * @param  ?bool  $mxRecordConfigured
     * @param  ?\novu\Models\Components\TestDomainRouteResponseDtoType  $type
     * @param  ?string  $wouldDeliverTo
     * @param  ?array<string, mixed>  $payload
     * @param  ?\novu\Models\Components\TestDomainRouteWebhookResultDto  $webhook
     * @param  ?\novu\Models\Components\TestDomainRouteAgentResultDto  $agent
     * @phpstan-pure
     */
    public function __construct(bool $matched, bool $dryRun, ?DomainStatus $domainStatus = null, ?bool $mxRecordConfigured = null, ?TestDomainRouteResponseDtoType $type = null, ?string $wouldDeliverTo = null, ?array $payload = null, ?TestDomainRouteWebhookResultDto $webhook = null, ?TestDomainRouteAgentResultDto $agent = null)
    {
        $this->matched = $matched;
        $this->dryRun = $dryRun;
        $this->domainStatus = $domainStatus;
        $this->mxRecordConfigured = $mxRecordConfigured;
        $this->type = $type;
        $this->wouldDeliverTo = $wouldDeliverTo;
        $this->payload = $payload;
        $this->webhook = $webhook;
        $this->agent = $agent;
    }
}