<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class TestDomainRouteDto
{
    /**
     *
     * @var \novu\Models\Components\TestDomainRouteFromDto $from
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\TestDomainRouteFromDto')]
    public TestDomainRouteFromDto $from;

    /**
     *
     * @var string $subject
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subject')]
    public string $subject;

    /**
     *
     * @var ?string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $text = null;

    /**
     *
     * @var ?string $html
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('html')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $html = null;

    /**
     * When true, returns the payload that would be delivered without invoking outbound webhooks or the agent HTTP endpoint.
     *
     * @var ?bool $dryRun
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dryRun')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $dryRun = null;

    /**
     * @param  \novu\Models\Components\TestDomainRouteFromDto  $from
     * @param  string  $subject
     * @param  ?string  $text
     * @param  ?string  $html
     * @param  ?bool  $dryRun
     * @phpstan-pure
     */
    public function __construct(TestDomainRouteFromDto $from, string $subject, ?string $text = null, ?string $html = null, ?bool $dryRun = null)
    {
        $this->from = $from;
        $this->subject = $subject;
        $this->text = $text;
        $this->html = $html;
        $this->dryRun = $dryRun;
    }
}