<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Text alignment for the email block */
enum TextAlignEnum: string
{
    case Center = 'center';
    case Left = 'left';
    case Right = 'right';
}
