<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** To - Novu subscriberId(s) allowed to settle this tool gate when HITL is enabled. */
class To
{

    public function __construct()
    {
    }
}