<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class TopicPayloadDto
{
    /**
     *
     * @var string $topicKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('topicKey')]
    public string $topicKey;

    /**
     *
     * @var TriggerRecipientsTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\TriggerRecipientsTypeEnum')]
    public TriggerRecipientsTypeEnum $type;

    /**
     * Optional array of subscriber IDs to exclude from the topic trigger
     *
     * @var ?array<string> $exclude
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exclude')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $exclude = null;

    /**
     * @param  string  $topicKey
     * @param  TriggerRecipientsTypeEnum  $type
     * @param  ?array<string>  $exclude
     * @phpstan-pure
     */
    public function __construct(string $topicKey, TriggerRecipientsTypeEnum $type, ?array $exclude = null)
    {
        $this->topicKey = $topicKey;
        $this->type = $type;
        $this->exclude = $exclude;
    }
}