<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** TranslationResponseDtoContent - Translation content as JSON object */
class TranslationResponseDtoContent
{

    public function __construct()
    {
    }
}