<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class UiSchemaProperty
{
    /**
     * Component type for the UI Schema Property
     *
     * @var UiComponentEnum $component
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('component')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\UiComponentEnum')]
    public UiComponentEnum $component;

    /**
     * Properties of the UI Schema
     *
     * @var ?array<string, UiSchemaProperty> $properties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('properties')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \novu\Models\Components\UiSchemaProperty>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $properties = null;

    /**
     * Placeholder for the UI Schema Property
     *
     * @var string|float|bool|array<string, mixed>|array<string|float|bool|array<string, mixed>>|null $placeholder
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('placeholder')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|array<string, mixed>|array<string|float|bool|array<string, mixed>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|array|null $placeholder = null;

    /**
     * @param  UiComponentEnum  $component
     * @param  ?array<string, UiSchemaProperty>  $properties
     * @param  string|float|bool|array<string, mixed>|array<string|float|bool|array<string, mixed>>|null  $placeholder
     * @phpstan-pure
     */
    public function __construct(UiComponentEnum $component, ?array $properties = null, string|float|bool|array|null $placeholder = null)
    {
        $this->component = $component;
        $this->properties = $properties;
        $this->placeholder = $placeholder;
    }
}