<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class UpdateSubscriberChannelRequestDto
{
    /**
     * The provider identifier for the credentials
     *
     * @var UpdateSubscriberChannelRequestDtoProviderId $providerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providerId')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\UpdateSubscriberChannelRequestDtoProviderId')]
    public UpdateSubscriberChannelRequestDtoProviderId $providerId;

    /**
     * Credentials payload for the specified provider
     *
     * @var ChannelCredentials $credentials
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('credentials')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\ChannelCredentials')]
    public ChannelCredentials $credentials;

    /**
     * The integration identifier
     *
     * @var ?string $integrationIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('integrationIdentifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $integrationIdentifier = null;

    /**
     * @param  UpdateSubscriberChannelRequestDtoProviderId  $providerId
     * @param  ChannelCredentials  $credentials
     * @param  ?string  $integrationIdentifier
     */
    public function __construct(UpdateSubscriberChannelRequestDtoProviderId $providerId, ChannelCredentials $credentials, ?string $integrationIdentifier = null)
    {
        $this->providerId = $providerId;
        $this->credentials = $credentials;
        $this->integrationIdentifier = $integrationIdentifier;
    }
}