<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class UpdateDomainDto
{
    /**
     * Replaces domain metadata when provided (max 10 keys, 500 characters total for keys+values).
     *
     * @var ?array<string, string> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $data = null;

    /**
     * @param  ?array<string, string>  $data
     * @phpstan-pure
     */
    public function __construct(?array $data = null)
    {
        $this->data = $data;
    }
}