<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** UpdateContextRequestDtoData - Custom data to associate with this context. Replaces existing data. */
class UpdateContextRequestDtoData
{

    public function __construct()
    {
    }
}