<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class UpdateWorkflowDtoProviders
{
    /**
     *
     * @var ?string $replyTo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('replyTo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $replyTo = null;

    /**
     * @param  ?string  $replyTo
     * @phpstan-pure
     */
    public function __construct(?string $replyTo = null)
    {
        $this->replyTo = $replyTo;
    }
}