<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class UpdateChannelConnectionRequestDto
{
    /**
     *
     * @var WorkspaceDto $workspace
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workspace')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\WorkspaceDto')]
    public WorkspaceDto $workspace;

    /**
     *
     * @var AuthDto $auth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('auth')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\AuthDto')]
    public AuthDto $auth;

    /**
     * @param  WorkspaceDto  $workspace
     * @param  AuthDto  $auth
     * @phpstan-pure
     */
    public function __construct(WorkspaceDto $workspace, AuthDto $auth)
    {
        $this->workspace = $workspace;
        $this->auth = $auth;
    }
}