<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;

use novu\Utils\SpeakeasyMetadata;
class UploadTranslationsRequestDto
{
    /**
     * The resource ID to associate localizations with. Accepts identifier or slug format
     *
     * @var string $resourceId
     */
    #[SpeakeasyMetadata('multipartForm:name=resourceId')]
    public string $resourceId;

    /**
     * The resource type to associate localizations with
     *
     * @var UploadTranslationsRequestDtoResourceType $resourceType
     */
    #[SpeakeasyMetadata('multipartForm:name=resourceType')]
    public UploadTranslationsRequestDtoResourceType $resourceType;

    /**
     * @param  string  $resourceId
     * @param  UploadTranslationsRequestDtoResourceType  $resourceType
     * @phpstan-pure
     */
    public function __construct(string $resourceId, UploadTranslationsRequestDtoResourceType $resourceType)
    {
        $this->resourceId = $resourceId;
        $this->resourceType = $resourceType;
    }
}