<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class UploadTranslationsResponseDto
{
    /**
     * Total number of files processed
     *
     * @var float $totalFiles
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalFiles')]
    public float $totalFiles;

    /**
     * Number of files successfully uploaded
     *
     * @var float $successfulUploads
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('successfulUploads')]
    public float $successfulUploads;

    /**
     * Number of files that failed to upload
     *
     * @var float $failedUploads
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failedUploads')]
    public float $failedUploads;

    /**
     * List of error messages for failed uploads
     *
     * @var array<string> $errors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $errors;

    /**
     * @param  float  $totalFiles
     * @param  float  $successfulUploads
     * @param  float  $failedUploads
     * @param  array<string>  $errors
     * @phpstan-pure
     */
    public function __construct(float $totalFiles, float $successfulUploads, float $failedUploads, array $errors)
    {
        $this->totalFiles = $totalFiles;
        $this->successfulUploads = $successfulUploads;
        $this->failedUploads = $failedUploads;
        $this->errors = $errors;
    }
}