<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class WebexRoomEndpointDto
{
    /**
     * Webex room ID
     *
     * @var string $roomId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('roomId')]
    public string $roomId;

    /**
     * Optional Webex parent message ID for threaded replies
     *
     * @var ?string $parentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parentId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $parentId = null;

    /**
     * @param  string  $roomId
     * @param  ?string  $parentId
     * @phpstan-pure
     */
    public function __construct(string $roomId, ?string $parentId = null)
    {
        $this->roomId = $roomId;
        $this->parentId = $parentId;
    }
}