<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class WebexPersonEndpointDto
{
    /**
     * Webex person ID. Provide exactly one of personId or personEmail.
     *
     * @var ?string $personId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('personId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $personId = null;

    /**
     * Webex person email. Provide exactly one of personId or personEmail.
     *
     * @var ?string $personEmail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('personEmail')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $personEmail = null;

    /**
     * @param  ?string  $personId
     * @param  ?string  $personEmail
     * @phpstan-pure
     */
    public function __construct(?string $personId = null, ?string $personEmail = null)
    {
        $this->personId = $personId;
        $this->personEmail = $personEmail;
    }
}