<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class WebhookEndpointDto
{
    /**
     * Webhook URL
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * Optional channel identifier
     *
     * @var ?string $channel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $channel = null;

    /**
     * @param  string  $url
     * @param  ?string  $channel
     * @phpstan-pure
     */
    public function __construct(string $url, ?string $channel = null)
    {
        $this->url = $url;
        $this->channel = $channel;
    }
}