<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** WorkflowResponseDtoLastName - User last name */
class WorkflowResponseDtoLastName
{

    public function __construct()
    {
    }
}