<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** Workflows - All translations for given locale organized by workflow identifier */
class Workflows
{

    public function __construct()
    {
    }
}