<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


class WorkflowPreferenceRequestDto
{
    /**
     * The workflow identifier
     *
     * @var string $workflowId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workflowId')]
    public string $workflowId;

    /**
     * Whether the preference is enabled. Used when condition is not provided.
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * Optional condition using JSON Logic rules
     *
     * @var ?array<string, mixed> $condition
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('condition')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $condition = null;

    /**
     * @param  string  $workflowId
     * @param  ?bool  $enabled
     * @param  ?array<string, mixed>  $condition
     * @phpstan-pure
     */
    public function __construct(string $workflowId, ?bool $enabled = null, ?array $condition = null)
    {
        $this->workflowId = $workflowId;
        $this->enabled = $enabled;
        $this->condition = $condition;
    }
}