<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace novu\Models\Components;


/** WorkflowListResponseDtoUpdatedBy - User who last updated the workflow */
class WorkflowListResponseDtoUpdatedBy
{
    /**
     * User ID
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_id')]
    public string $id;

    /**
     * User first name
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     * User last name
     *
     * @var ?WorkflowListResponseDtoLastName $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    #[\Speakeasy\Serializer\Annotation\Type('\novu\Models\Components\WorkflowListResponseDtoLastName|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WorkflowListResponseDtoLastName $lastName = null;

    /**
     * User external ID
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     * @param  string  $id
     * @param  ?string  $firstName
     * @param  ?WorkflowListResponseDtoLastName  $lastName
     * @param  ?string  $externalId
     * @phpstan-pure
     */
    public function __construct(string $id, ?string $firstName = null, ?WorkflowListResponseDtoLastName $lastName = null, ?string $externalId = null)
    {
        $this->id = $id;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->externalId = $externalId;
    }
}